/** Re-export shared soft-group helpers for first-party extensions. */
export {
	SoftGroupTracker,
	SynchronizedShimmerRender,
	bindSoftGroupTracker,
	formatLiveToolDuration,
	formatToolDuration,
	renderSoftGroupedCall,
	renderSynchronizedShimmerLine,
	liveToolElapsedMs,
	resetToolActivity,
	seedSessionTopology,
	syncToolActivity,
	type SoftGroupItem,
	type SoftGroupStreak,
	type SoftGroupRenderContext,
	type SoftGroupedCallTheme,
	type ToolActivityRenderContext,
	type ToolActivitySnapshot,
	type ToolActivityTheme,
} from "../pi-tui-soft-group/index.ts";
